
py_library(
    name='spike',
    srcs=[
        '__init__.py',
    ],
)


py_test(
    name='test_spike',
    srcs=[
        'tests/test_spike.py',
    ],
    deps=[
        ':spike',
    ],
    size = 'small',
)
